// src/lib/aryan_hosteldata.js

export const studentHostelData = [
  {
    id: 1,
    name: "Arjun Mehta",
    rollNo: "18349201",
    enrolmentNo: "2025110001",
    dob: "2003-05-12",
    photo: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg",

    hostel: {
      hostelName: "Bhagirathi Bhawan",
      roomNumber: "A-203",
      block: "A",
      floor: 2,
      bedNumber: "B",
      roomType: "Double",
      occupancy: 2,
      attachedWashroom: false,
      roomStatus: "Allotted",
      hostelFee: "₹40,000/year",
      paymentStatus: "Paid",
      lastPaymentDate: "2025-06-15",
      wardenName: "Mr. Sunil Sharma",
      wardenPhone: "9876543210",
      wardenEmail: "warden.hostel@college.com",
      allocationDate: "2025-07-01",
      admissionYear: 2025,
    },

    complaints: [
      {
        id: 1,
        date: "2025-08-01",
        issue: "Fan not working",
        status: "Resolved",
      },
      {
        id: 2,
        date: "2025-09-11",
        issue: "Water leakage in washroom",
        status: "Pending",
      },
    ],
  },

  {
    id: 2,
    name: "Neha Singh",
    rollNo: "18349202",
    enrolmentNo: "2025110002",
    dob: "2003-08-02",
    photo: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg",

    hostel: {
      hostelName: "Ganga Bhawan",
      roomNumber: "B-101",
      block: "B",
      floor: 1,
      bedNumber: "A",
      roomType: "Single",
      occupancy: 1,
      attachedWashroom: true,
      roomStatus: "Allotted",
      hostelFee: "₹50,000/year",
      paymentStatus: "Paid",
      lastPaymentDate: "2025-07-01",
      wardenName: "Mrs. Kavita Rao",
      wardenPhone: "9876500001",
      wardenEmail: "warden.ganga@college.com",
      allocationDate: "2025-07-10",
      admissionYear: 2025,
    },

    complaints: [],
  },

  {
    id: 3,
    name: "Rohit Verma",
    rollNo: "18349203",
    enrolmentNo: "2025110003",
    dob: "2004-02-20",
    photo: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg",

    hostel: {
      hostelName: "Yamuna Bhawan",
      roomNumber: "C-403",
      block: "C",
      floor: 4,
      bedNumber: "C",
      roomType: "Triple",
      occupancy: 3,
      attachedWashroom: false,
      roomStatus: "Allotted",
      hostelFee: "₹35,000/year",
      paymentStatus: "Pending",
      lastPaymentDate: "-",
      wardenName: "Mr. Rakesh Sinha",
      wardenPhone: "9876522220",
      wardenEmail: "warden.yamuna@college.com",
      allocationDate: "2025-06-28",
      admissionYear: 2025,
    },

    complaints: [
      {
        id: 1,
        date: "2025-10-05",
        issue: "Window broken",
        status: "In Progress",
      },
    ],
  },

  {
    id: 4,
    name: "Simran Kaur",
    rollNo: "18349204",
    enrolmentNo: "2025110004",
    dob: "2004-11-11",
    photo: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg",

    hostel: {
      hostelName: "Saraswati Bhawan",
      roomNumber: "D-305",
      block: "D",
      floor: 3,
      bedNumber: "A",
      roomType: "Double",
      occupancy: 2,
      attachedWashroom: true,
      roomStatus: "Allotted",
      hostelFee: "₹42,000/year",
      paymentStatus: "Paid",
      lastPaymentDate: "2025-06-25",
      wardenName: "Mrs. Ritu Sharma",
      wardenPhone: "9876541111",
      wardenEmail: "warden.saraswati@college.com",
      allocationDate: "2025-07-01",
      admissionYear: 2025,
    },

    complaints: [],
  },

  {
    id: 5,
    name: "Aditya Kumar",
    rollNo: "18349205",
    enrolmentNo: "2025110005",
    dob: "2003-07-04",
    photo: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg",

    hostel: {
      hostelName: "Bhagirathi Bhawan",
      roomNumber: "A-102",
      block: "A",
      floor: 1,
      bedNumber: "B",
      roomType: "Triple",
      occupancy: 3,
      attachedWashroom: false,
      roomStatus: "Allotted",
      hostelFee: "₹38,000/year",
      paymentStatus: "Paid",
      lastPaymentDate: "2025-06-20",
      wardenName: "Mr. Sunil Sharma",
      wardenPhone: "9876543210",
      wardenEmail: "warden.hostel@college.com",
      allocationDate: "2025-07-03",
      admissionYear: 2025,
    },

    complaints: [
      { id: 1, date: "2025-09-01", issue: "Noise disturbance", status: "Resolved" },
    ],
  },
];
